Added mechanism to run scripts provided with a database.

diff --git a/bin/mella b/bin/mella
--- a/bin/mella
+++ b/bin/mella
@@ -14,6 +14,7 @@ function help() {
 	echo "  get <db> [args]  Download database <db> with possible arguments"
 	echo "  args <db>        List arguments for database Makefile"
 	echo "  list             List available databases to download"
+	echo "  run <db> [args]  Run scripts for database <db> with possible arguments"
 	echo "  help             Display this help"
 	echo
 	echo "mella is the apiarius database downloader."
@@ -92,6 +93,38 @@ elif [[ $1 == "get" ]]; then
 		exit 1
 
 	fi
+
+elif [[ $1 == "run" ]]; then
+
+	if (( $# >= 2 )); then
+
+		dbname=$2
+		dbhome=$basepath/db/$dbname
+
+		if (( $# >= 3 )); then
+
+			script=$3
+			if [[ -x $dbhome/$script ]]; then
+				$dbhome/$script
+			else
+				echo "Error: script does not exist or is not executable"
+				exit 1
+			fi
+
+		else
+			
+			find $dbhome -maxdepth 1 -executable -type f -printf "%f\n"
+		
+		fi
+
+	else
+
+		help
+		echo "Error: no database specified"
+		exit 1
+
+	fi
+
 
 else
 
